pipeline {
    agent {
        docker {
            image 'docker.internal.kevinlin.info/infra/ci-base:0.1.1'
            label 'docker-executor'
        }
    }

    options {
        withAWS(
            endpointUrl: 'https://storage.kevinlin.info',
            credentials: 'storage-internal',
        )
    }

    stages {
        stage('Environment') {
            steps {
                s3Download(
                    bucket: 'internal',
                    path: 'resources/orion-web/.env',
                    file: '.env',
                )
            }
        }
        stage('Install') {
            steps {
                sh 'npm install'
            }
        }
        stage('Test') {
            parallel {
                stage('Lint') {
                    steps {
                        sh 'npm run lint'
                    }
                }
                stage('Unit') {
                    steps {
                        sh 'npm run test'
                    }
                }
            }
        }
        stage('Build') {
            environment {
                NODE_ENV = 'production'
            }
            steps {
                sh 'npm run build'
            }
        }
        stage('Release') {
            steps {
                sh 'tar -czf release.tar.gz dist/'
                s3Upload(
                    bucket: 'internal',
                    path: "deploy/${env.JOB_NAME}/${env.GIT_COMMIT}/",
                    file: 'release.tar.gz',
                )
            }
        }
    }
}
